# Generated by Django 5.0.1 on 2024-01-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created'], 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
    ]
